Support for the kumler_bauer projection in coords2rtheta
Visual-Behavior/aloception-oss pull request #227
Opened 2022-09-27 09:12 UTC by tflahaul

Support for the kumler_bauer projection in coords2rtheta

* ***New feature 1*** : 
```python
coords2rtheta(..., distortion=(0.25, 0.45), projection="kumler_bauer")
```
```python
coords2rtheta(..., distortion=0.25, projection="kumler_bauer") # same value is used for alpha and beta
```
_____
This pull request includes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

2022-09-30 13:44 UTC, Data-Iab approved these changes

2022-10-03 07:17 UTC, anhtu293 approved these changes

2022-10-03 07:43 UTC, Data-Iab requested changes

2022-10-03 07:43 UTC, Data-Iab commented on aloscene/utils/depth_utils.py
> +        assert not isinstance(distortion, Sequence)
The input is never an instance of Sequence. I suppose you mean : `assert isinstance(distortion, float)` ?

2022-10-03 07:43 UTC, Data-Iab commented on aloscene/utils/depth_utils.py
> +        assert isinstance(distortion, Sequence), "Kumler-Bauer projection needs two distortion coefficients (alpha, beta)"
Same as above.
```python
assert isinstance(distortion, (tuple, list))
assert len(distortion) == 2
```

2022-10-04 15:14 UTC, merged