Fix merge tensor dict child
Visual-Behavior/aloception-oss pull request #304
Opened 2022-11-18 15:31 UTC by jsalotti

General description of your pull request with the list of new features and/or bugs.

* ***New feature 1*** : Description
```python
# Python code snippet showing how to use it.
```

* ***New feature 2*** : Description
```python
# Python code snippet showing how to use it.
```

* ***Fix bug X*** : Description

_____
This pull request includes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2022-11-22 06:47 UTC, thibo73800 requested changes
Can you provide this PR with a new set of unit test to check compatibility with previous behavior + exposing the different new possible scenarios ?

2022-11-28 12:22 UTC, Data-Iab approved these changes
Tested.
Will be merged once @thibo73800 approves

2023-01-16 13:44 UTC, jsalotti commented
@Data-Iab Unittests have been added ; and an error fixed. The branch is now ready to be merged.

2023-01-16 15:55 UTC, Data-Iab approved these changes

2023-01-16 15:57 UTC, merged