added .npz support to load_depth function
Visual-Behavior/aloception-oss pull request #342
Opened 2023-03-17 14:30 UTC by Dee61298

Now you can also use this function to load depth saved as .npz. Based on the fix I made for MOTSynth dataset.

_____
This pull request includes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-03-22 08:47 UTC, Data-Iab requested changes

2023-03-22 08:47 UTC, Data-Iab commented on aloscene/io/depth.py
> +        return np.load(path)["arr_0"]
This key-specific, not all .npz have `"arr_0"` as a key

2023-04-06 12:24 UTC, thibo73800 approved these changes

2023-04-06 12:26 UTC, thibo73800 approved these changes

2023-04-06 12:28 UTC, thibo73800 commented on aloscene/io/depth.py
> +        return list(np.load(path).values())
Not sure we want to return the list of delement here. I think we want to retrun only one depth element assuming only one depth is inside the npz. Somethine link
```
content = np.load(path)
return content[content.keys()[0]]
```

2023-04-14 07:38 UTC, Data-Iab approved these changes

2023-04-14 07:38 UTC, merged